enum ThemeType {
  INITIAL_CLUE,
  HINTED_CLUE,
  USER_ENTERED,
  NOTE,
  HIGHLIGHT,
  BACKGROUND,
  UNEDITABLE_CELL_BACKGROUND,
  INCORRECT,
  SELECTED,
  NUMERIC_SELECTION_BACKGROUND,
  NUMERIC_SELECTION_TEXT,
  BUTTON_BACKGROUND,
  BUTTON_TEXT
}